/**
 * Starts a disposable Jellyfin container for local development, runs the first-time
 * wizard and creates an API key. Writes .env.local when it does not exist yet (or with
 * --write-env), otherwise prints the env lines to put there.
 *
 *   pnpm jellyfin:dev                 # port 8096
 *   PORT=18096 pnpm jellyfin:dev
 *   pnpm jellyfin:dev --write-env     # overwrite .env.local
 *
 * Stop it with `docker rm -f jellycrew-dev-jellyfin`.
 */
import { execFileSync } from "node:child_process";
import { randomBytes } from "node:crypto";
import fs from "node:fs";
import { JELLYFIN_IMAGE } from "../lib/jellyfin/version";
import { bootstrapJellyfin } from "../tests/integration/harness/jellyfin";

const NAME = "jellycrew-dev-jellyfin";
const port = Number(process.env.PORT ?? 8096);

async function waitForApi(url: string) {
  const deadline = Date.now() + 180_000;
  while (Date.now() < deadline) {
    try {
      const res = await fetch(`${url}/System/Info/Public`);
      if (res.ok && (await res.text()).includes('"Version"')) return;
    } catch {
      // not up yet
    }
    await new Promise((r) => setTimeout(r, 1000));
  }
  throw new Error("Jellyfin did not become ready");
}

async function main() {
  execFileSync("docker", ["rm", "-f", NAME], { stdio: "ignore" });
  execFileSync("docker", ["run", "-d", "--name", NAME, "-p", `${port}:8096`, JELLYFIN_IMAGE], { stdio: "ignore" });
  const url = `http://localhost:${port}`;
  await waitForApi(url);
  const server = await bootstrapJellyfin(url, "jellycrew-dev");
  console.log(`# Jellyfin ${JELLYFIN_IMAGE} running as ${NAME}`);
  console.log(`# admin login: ${server.admin.name} / ${server.admin.password}`);
  const lines = [
    "# Local development. Generated by scripts/dev-jellyfin.ts.",
    `JELLYFIN_URL=${server.url}`,
    `JELLYFIN_API_KEY=${server.apiKey}`,
    "PUBLIC_BASE_URL=http://localhost:3000",
    "DATA_DIR=./data",
    `SESSION_SECRET=${randomBytes(32).toString("hex")}`,
    "# SMTP_URL=smtp://localhost:1025",
    '# SMTP_FROM="Jellyfin <noreply@example.test>"',
    "LOG_LEVEL=info",
    "LOG_PRETTY=1",
    "",
  ];
  const writeEnv = process.argv.includes("--write-env") || !fs.existsSync(".env.local");
  if (writeEnv) {
    fs.writeFileSync(".env.local", lines.join("\n"));
    console.log("# wrote .env.local — run `pnpm dev`");
  } else {
    console.log("# .env.local exists; update these values in it (or rerun with --write-env):");
    console.log(`JELLYFIN_URL=${server.url}`);
    console.log(`JELLYFIN_API_KEY=${server.apiKey}`);
  }
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
